"""
플랫폼 서비스 패키지
- 브랜드, Feature, 설정, 분석, 모니터링 서비스
"""

# Config Manager
from app.services.platform.config_manager import (
    ConfigManager,
    ConfigType,
    ConfigEntry,
    ConfigManagerMetrics,
    EnvVarProcessor,
    ConfigValidator,
    get_config_manager,
    load_brand_config,
    load_platform_config,
    list_brands,
)

# Brand Manager
from app.services.platform.brand_manager import (
    BrandManager,
    BrandInfo,
    BrandStatus,
    BrandStats,
    ValidationResult,
    ValidationLevel,
    BrandValidator,
    get_brand_manager,
    get_brand,
    validate_brand,
    get_brand_stats,
)

# Feature Manager
from app.services.platform.feature_manager import (
    FeatureManager,
    FeatureInfo,
    FeatureStatus,
    FeatureValidationResult,
    ValidationIssue,
    ValidationSeverity,
    FeatureManagerMetrics,
    SchemaLoader,
    get_feature_manager,
    validate_feature_config,
    list_features,
    is_feature_enabled,
)

# Analytics Service
from app.services.platform.analytics import (
    AnalyticsService,
    AnalyticsConfig,
    AnalyticsMetrics,
    Event,
    EventType,
    AggregationType,
    TimeWindow,
    TimeSeriesAggregator,
    EventHandler,
    LoggingEventHandler,
    CallbackEventHandler,
    get_analytics_service,
    create_analytics_service,
    track_event,
    track_query,
    track_error,
)

# Monitoring Service
from app.services.platform.monitoring import (
    MonitoringService,
    MonitoringConfig,
    MonitoringMetrics,
    ServiceHealth,
    SystemHealth,
    Alert,
    HealthStatus,
    ServiceType,
    AlertLevel,
    HealthChecker,
    Neo4jHealthChecker,
    RedisHealthChecker,
    LLMHealthChecker,
    VectorHealthChecker,
    get_monitoring_service,
    create_monitoring_service,
    health_check,
    get_system_stats,
    get_alerts,
)

__all__ = [
    # Config Manager
    "ConfigManager",
    "ConfigType",
    "ConfigEntry",
    "ConfigManagerMetrics",
    "EnvVarProcessor",
    "ConfigValidator",
    "get_config_manager",
    "load_brand_config",
    "load_platform_config",
    "list_brands",
    # Brand Manager
    "BrandManager",
    "BrandInfo",
    "BrandStatus",
    "BrandStats",
    "ValidationResult",
    "ValidationLevel",
    "BrandValidator",
    "get_brand_manager",
    "get_brand",
    "validate_brand",
    "get_brand_stats",
    # Feature Manager
    "FeatureManager",
    "FeatureInfo",
    "FeatureStatus",
    "FeatureValidationResult",
    "ValidationIssue",
    "ValidationSeverity",
    "FeatureManagerMetrics",
    "SchemaLoader",
    "get_feature_manager",
    "validate_feature_config",
    "list_features",
    "is_feature_enabled",
    # Analytics
    "AnalyticsService",
    "AnalyticsConfig",
    "AnalyticsMetrics",
    "Event",
    "EventType",
    "AggregationType",
    "TimeWindow",
    "TimeSeriesAggregator",
    "EventHandler",
    "LoggingEventHandler",
    "CallbackEventHandler",
    "get_analytics_service",
    "create_analytics_service",
    "track_event",
    "track_query",
    "track_error",
    # Monitoring
    "MonitoringService",
    "MonitoringConfig",
    "MonitoringMetrics",
    "ServiceHealth",
    "SystemHealth",
    "Alert",
    "HealthStatus",
    "ServiceType",
    "AlertLevel",
    "HealthChecker",
    "Neo4jHealthChecker",
    "RedisHealthChecker",
    "LLMHealthChecker",
    "VectorHealthChecker",
    "get_monitoring_service",
    "create_monitoring_service",
    "health_check",
    "get_system_stats",
    "get_alerts",
]
